title: "Xihang Chen"
author: "Xihang Chen"
description: "Researcher in Health Data Science at NDORMS, University of Oxford."
permalink: /:title/
lang: "en"
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - UNLICENSE.txt
  - vendor
  - .bundle
  - .bundle_home

# Menu

navigation:
  - {file: "index.html"}
  - {file: "mis.html"}

external:
  - {title: Work Mail, icon: envelope, url: "mailto:xihang.chen@ndorms.ox.ac.uk"}
  - {title: Github, icon: github, url: "https://github.com/chen-xihang"}
  - {title: LinkedIn, icon: linkedin, url: "https://uk.linkedin.com/in/xihang-chen-7a1658221"}
